"""baseline v3.2

Revision ID: 819ead62a00a
Revises: 
Create Date: 2026-06-27 21:25:52.252230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '819ead62a00a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Host',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('NiktoIncident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osvdb_id', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OpenVASVulnerability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nvt_oid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('severity_score', sa.Float(precision=3), nullable=True),
    sa.Column('severity_class', sa.String(length=20), nullable=True),
    sa.Column('cvss_base_score', sa.Float(precision=3), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('cve_ids', sa.Text(), nullable=True),
    sa.Column('cert_refs', sa.Text(), nullable=True),
    sa.Column('bugtraq_ids', sa.Text(), nullable=True),
    sa.Column('other_refs', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('affected_software', sa.Text(), nullable=True),
    sa.Column('solution_type', sa.String(length=50), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('qod_value', sa.Integer(), nullable=True),
    sa.Column('qod_type', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OpenVASVulnerability_nvt_oid'), 'OpenVASVulnerability', ['nvt_oid'], unique=True)
    op.create_index(op.f('ix_OpenVASVulnerability_severity_class'), 'OpenVASVulnerability', ['severity_class'], unique=False)
    op.create_table('Port',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol')
    )
    op.create_table('Topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('password_salt', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('AccessToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AccessToken_token'), 'AccessToken', ['token'], unique=True)
    op.create_table('Document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('is_ai_generated', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IrisAnalysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProgramedScan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule_type', sa.String(length=10), nullable=False),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RefreshToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RefreshToken_token'), 'RefreshToken', ['token'], unique=True)
    op.create_table('ScanFolder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Traceroute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('hops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hop_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target', name='unique_user_target_trace')
    )
    op.create_index(op.f('ix_Traceroute_target'), 'Traceroute', ['target'], unique=False)
    op.create_index(op.f('ix_Traceroute_user_id'), 'Traceroute', ['user_id'], unique=False)
    op.create_table('UserAttribute',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'attribute_name')
    )
    op.create_table('Vault',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checker', sa.String(length=512), nullable=False),
    sa.Column('vault_key', sa.String(length=512), nullable=False),
    sa.Column('transformation', sa.String(length=64), nullable=False),
    sa.Column('kdf', sa.String(length=64), nullable=False),
    sa.Column('kdf_iterations', sa.Integer(), nullable=False),
    sa.Column('kdf_memory', sa.Integer(), nullable=False),
    sa.Column('kdf_parallelism', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('AegisDocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('closing', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Document.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['Topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IrisDocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['IrisAnalysis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['Document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IrisRuleResult',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['IrisAnalysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('frecuent', sa.Boolean(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('programed_scan_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['ScanFolder.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['Host.id'], ),
    sa.ForeignKeyConstraint(['programed_scan_id'], ['ProgramedScan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Storable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['Vault.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'vault_id', name='uq_storable_vault_title'),
    sa.UniqueConstraint('vault_id', 'internal_id', name='uq_storable_vault_internal')
    )
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AegisDocumentAlert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_label', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('published', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('affected_brands', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['AegisDocument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'position', name='uq_alert_document_position')
    )
    op.create_table('AegisTip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('links_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['AegisDocument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'position', name='uq_tip_document_position')
    )
    op.create_table('BankAccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=512), nullable=False),
    sa.Column('holder', sa.String(length=512), nullable=False),
    sa.Column('iban', sa.String(length=512), nullable=False),
    sa.Column('swift_bic', sa.String(length=512), nullable=False),
    sa.Column('account_number', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CreditCard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardholder_name', sa.String(length=512), nullable=False),
    sa.Column('card_number', sa.String(length=512), nullable=False),
    sa.Column('expiration_date', sa.String(length=512), nullable=False),
    sa.Column('postal_code', sa.String(length=512), nullable=False),
    sa.Column('cvv', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=512), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=512), nullable=False),
    sa.Column('country', sa.String(length=512), nullable=False),
    sa.Column('document_id', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NiktoScan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NmapScan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OpenVASScan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('report_id', sa.String(length=255), nullable=False),
    sa.Column('scan_config_name', sa.String(length=255), nullable=True),
    sa.Column('scanner_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'report_id', name='unique_task_report')
    )
    op.create_table('SecureNote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SentinelDocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('enrichment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Document.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['Scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SoftwareLicense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=512), nullable=False),
    sa.Column('license_key', sa.String(length=512), nullable=False),
    sa.Column('licensed_to', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WifiNetwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssid', sa.String(length=512), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('security_type', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Storable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OpenPort',
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('nmap_scan_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('given_use', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['nmap_scan_id'], ['NmapScan.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['Port.id'], ),
    sa.PrimaryKeyConstraint('port_id', 'nmap_scan_id')
    )
    op.create_table('OpenVASScanResult',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openvas_scan_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['Host.id'], ),
    sa.ForeignKeyConstraint(['openvas_scan_id'], ['OpenVASScan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['OpenVASVulnerability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OpenVASScanResult_host_id'), 'OpenVASScanResult', ['host_id'], unique=False)
    op.create_index(op.f('ix_OpenVASScanResult_openvas_scan_id'), 'OpenVASScanResult', ['openvas_scan_id'], unique=False)
    op.create_index(op.f('ix_OpenVASScanResult_vulnerability_id'), 'OpenVASScanResult', ['vulnerability_id'], unique=False)
    op.create_table('ScanIncident',
    sa.Column('nikto_scan_id', sa.Integer(), nullable=False),
    sa.Column('nikto_incident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nikto_incident_id'], ['NiktoIncident.id'], ),
    sa.ForeignKeyConstraint(['nikto_scan_id'], ['NiktoScan.id'], ),
    sa.PrimaryKeyConstraint('nikto_scan_id', 'nikto_incident_id')
    )
    op.create_table('TargetPort',
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('nmap_scan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nmap_scan_id'], ['NmapScan.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['Port.id'], ),
    sa.PrimaryKeyConstraint('port_id', 'nmap_scan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TargetPort')
    op.drop_table('ScanIncident')
    op.drop_index(op.f('ix_OpenVASScanResult_vulnerability_id'), table_name='OpenVASScanResult')
    op.drop_index(op.f('ix_OpenVASScanResult_openvas_scan_id'), table_name='OpenVASScanResult')
    op.drop_index(op.f('ix_OpenVASScanResult_host_id'), table_name='OpenVASScanResult')
    op.drop_table('OpenVASScanResult')
    op.drop_table('OpenPort')
    op.drop_table('WifiNetwork')
    op.drop_table('SoftwareLicense')
    op.drop_table('SentinelDocument')
    op.drop_table('SecureNote')
    op.drop_table('OpenVASScan')
    op.drop_table('NmapScan')
    op.drop_table('NiktoScan')
    op.drop_table('Identity')
    op.drop_table('CreditCard')
    op.drop_table('BankAccount')
    op.drop_table('AegisTip')
    op.drop_table('AegisDocumentAlert')
    op.drop_table('Account')
    op.drop_table('Storable')
    op.drop_table('Scan')
    op.drop_table('IrisRuleResult')
    op.drop_table('IrisDocument')
    op.drop_table('AegisDocument')
    op.drop_table('Vault')
    op.drop_table('UserAttribute')
    op.drop_index(op.f('ix_Traceroute_user_id'), table_name='Traceroute')
    op.drop_index(op.f('ix_Traceroute_target'), table_name='Traceroute')
    op.drop_table('Traceroute')
    op.drop_table('ScanFolder')
    op.drop_index(op.f('ix_RefreshToken_token'), table_name='RefreshToken')
    op.drop_table('RefreshToken')
    op.drop_table('ProgramedScan')
    op.drop_table('IrisAnalysis')
    op.drop_table('Document')
    op.drop_index(op.f('ix_AccessToken_token'), table_name='AccessToken')
    op.drop_table('AccessToken')
    op.drop_table('User')
    op.drop_table('Topic')
    op.drop_table('Port')
    op.drop_index(op.f('ix_OpenVASVulnerability_severity_class'), table_name='OpenVASVulnerability')
    op.drop_index(op.f('ix_OpenVASVulnerability_nvt_oid'), table_name='OpenVASVulnerability')
    op.drop_table('OpenVASVulnerability')
    op.drop_table('NiktoIncident')
    op.drop_table('Host')
    # ### end Alembic commands ###
