"""
Database models for shared entities.

This module contains SQLAlchemy base classes and the Document model,
which serves as the base for all generated documents in the system.

Classes:
    Base: SQLAlchemy declarative base for all models.
    Document: Base model for all generated documents (PDF, JSON, MD).

Example:
>>> from src.modules.shared import Base, Document
>>> from sqlalchemy import create_engine
>>> engine = create_engine("sqlite:///:memory:")
>>> Base.metadata.create_all(engine)
"""

from datetime import datetime

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import relationship, declarative_base


Base = declarative_base()


class Document(Base):
    """
    Base model for any document generated by the system.

    Uses joined-table inheritance (same as Scan): each subclass defines
    its own table with specific fields and inherits these via FK.

    This model stores metadata common to all document types, while
    subclasses like AegisDocument and SentinelDocument define their
    specific attributes.

    Attributes:
        id: Primary key, auto-incrementing integer.
        document_type: Polymorphic discriminator ('aegis' | 'sentinel').
        filename: Relative path to the file on disk.
        format: Document format ('pdf' | 'json' | 'md').
        status: Generation status ('pending' | 'running' | 'done' | 'error').
        created_at: Timestamp when the record was created (automatic).
        generated_at: Timestamp when generation completed (nullable).
        is_ai_generated: Flag indicating if content was AI-generated (default: 1).
        user_id: Foreign key to User.
        user: User relationship.

    Subclasses:
        AegisDocument: Security awareness pills.
        SentinelDocument: Scan reports.

    Auto-generated fields (DO NOT assign manually):
        id, document_type, created_at

    Example:
    >>> doc = Document(
    ...     document_type='sentinel',
    ...     filename='reports/scan_123.pdf',
    ...     format='pdf',
    ...     status='done',
    ...     user_id=1
    ... )
    >>> print(doc)
    '<Document(id=None, type='sentinel', status='done', user_id=1)>'
    """

    __tablename__ = "Document"

    id            = Column(Integer,     primary_key=True, autoincrement=True)
    document_type = Column(String(30),  nullable=False)

    filename      = Column(String(256), nullable=False)
    format        = Column(String(10),  nullable=False)

    status          = Column(String(20),  nullable=False, default="pending")
    created_at      = Column(DateTime,    nullable=False, default=datetime.utcnow)
    generated_at    = Column(DateTime,    nullable=True)
    is_ai_generated = Column(Integer,     nullable=False, default=1)

    user_id       = Column(Integer, ForeignKey("User.id"), nullable=False)
    user          = relationship("User", back_populates="documents")

    __mapper_args__ = {
        "polymorphic_identity": "document",
        "polymorphic_on":       document_type,
    }

    def __repr__(self) -> str:
        """
        Return a string representation of the Document instance.

        Returns:
            String representation showing id, type, status, and user_id.
        """
        return (
            f"<Document(id={self.id}, type='{self.document_type}', "
            f"status='{self.status}', user_id={self.user_id})>"
        )