version: '3.9'
services:
  openvas:
    image: immauss/openvas:latest
    container_name: openvas
    restart: unless-stopped
    ports:
      - "9392:9392"
      - "9390:9390"
    volumes:
      - openvas-data:/data
    environment:
      - PASSWORD=admin123
      - SKIPSYNC=true
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 208.67.222.222
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_PTRACE

    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G
    shm_size: 1gb

volumes:
  openvas-data: