services:
  ollama:
    image: ollama/ollama:latest
    container_name: OllamaSeQ
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      OLLAMA_MODEL: ${OLLAMA_MODEL:-mistral}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<> /dev/tcp/localhost/11434; echo -e \"GET /api/version HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n\" >&3; cat <&3 | grep -q \"200 OK\"'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    # GPU NVIDIA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_models: