"""
Database models for Aegis security awareness module.

This module contains SQLAlchemy models for generating security awareness
content including topics, awareness pills (documents), tips, and vulnerability
alerts from external sources like INCIBE and NVD.

Classes:
    Topic: Category/topic for organizing awareness documents.
    AegisDocument: Security awareness pill (polymorphic from Document).
    AegisTip: Individual security tip within a document.
    AegisDocumentAlert: Vulnerability alert from external sources.

Example:
    >>> from src.modules.aegis.model import AegisDocument, Topic
    >>> doc = AegisDocument(title="Phishing Awareness", topic_id=1, user_id=1)
    >>> print(doc)
    <AegisDocument(id=None, topic_id=1, status='pending')>
"""

from datetime import datetime

from sqlalchemy import (
    ARRAY,
    Column,
    Date,
    ForeignKey,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship

from src.modules.shared import Base, Document


# =========================================================================
# TOPIC MODEL
# =========================================================================

class Topic(Base):
    """
    Category/topic for organizing security awareness documents.

    Defines the available topics for Aegis content generation, such as
    "Phishing", "Password Security", "Social Engineering", etc.

    Attributes:
        id: Primary key, auto-incrementing integer.
        title: Topic name (max 64 characters).
    """
    __tablename__ = "Topic"

    id    = Column(Integer,     primary_key=True, autoincrement=True)
    title = Column(String(128),  nullable=False)

    documents = relationship("AegisDocument", back_populates="topic")


# =========================================================================
# AEGIS DOCUMENT
# =========================================================================

class AegisDocument(Document):
    """
    Security awareness document (pill) generated by Aegis.

    Inherits from Document (shared model):
        id, document_type, filename, format, status,
        created_at, generated_at, user_id, user

    Stores the content of the generated awareness pill including
    title, subtitle, introduction, closing, and associated tips/alerts.

    Attributes:
        id: Primary key (foreign key to Document.id).
        title: Internal identifier/placeholder during pending state.
        subtitle: Creative title generated by AI (visible to user).
        intro: Extensive introduction content.
        closing: Conclusion/call to action.
        contact_email: Contact email shown in the document.
        company: Target company for the document.
        topic_id: Foreign key to Topic.id.
        topic: Topic relationship.
        tips: List of AegisTip objects (ordered by position).
        alerts: List of AegisDocumentAlert objects (ordered by position).

    Note on 'generated_at':
        In the previous model AegisDocument had its own generated_at with
        default=datetime.utcnow (always filled). Now it lives in Document
        as nullable=True and is assigned when generation completes,
        same as the 'status' field. AegisManager must assign it in
        _update_document_status when status changes to 'done'.
    """

    __tablename__ = "AegisDocument"

    id            = Column(Integer,     ForeignKey("Document.id"), primary_key=True)

    # Identificación interna
    title         = Column(String(128), nullable=False)

    # Contenido de la píldora
    subtitle      = Column(String(256), nullable=True)
    intro         = Column(Text,        nullable=True)
    closing       = Column(Text,        nullable=True)
    contact_email = Column(String(128), nullable=True)
    company       = Column(String(128), nullable=True)

    # Relación con el tema
    topic_id      = Column(Integer, ForeignKey("Topic.id"), nullable=False)
    topic         = relationship("Topic", back_populates="documents")

    tips = relationship(
        "AegisTip",
        back_populates="document",
        order_by="AegisTip.position",
        cascade="all, delete-orphan",
    )
    alerts = relationship(
        "AegisDocumentAlert",
        back_populates="document",
        order_by="AegisDocumentAlert.position",
        cascade="all, delete-orphan",
    )

    __mapper_args__ = {
        "polymorphic_identity": "aegis",
    }

    def pill_to_dict(self) -> dict:
        """
        Serialize the pill content for API responses.

        Returns:
            Dictionary with subtitle, intro, tips, closing, contactEmail, and company.
        """
        return {
            "subtitle":     self.subtitle or "",
            "intro":        self.intro or "",
            "tips":         [t.to_dict() for t in self.tips],
            "closing":      self.closing or "",
            "contactEmail": self.contact_email or "",
            "company":      self.company or "",
        }

    def __repr__(self) -> str:
        """
        Return a debug representation of the AegisDocument instance.

        Returns:
            String with id, topic_id, and status.
        """
        return (
            f"<AegisDocument(id={self.id}, topic_id={self.topic_id}, "
            f"status='{self.status}')>"
        )


# =========================================================================
# TIPS AND ALERTS
# =========================================================================

class AegisTip(Base):
    """
    Individual security tip within an AegisDocument.

    Represents a single piece of advice with a headline and body text,
    optionally including external links for further reading.

    Attributes:
        id: Primary key, auto-incrementing integer.
        document_id: Foreign key to AegisDocument.id.
        position: Order of the tip within the document (1-based).
        headline: Action or risk summarized in a phrase.
        body: Development of the tip (2-3 sentences).
        links_json: JSONB with list of {text, url}; NULL or [] if no links.

    Table Constraints:
        Unique constraint on (document_id, position) to prevent duplicates.

    Example of links_json:
        [{"text": "uBlock Origin", "url": "https://github.com/gorhill/uBlock"}]
    """

    __tablename__ = "AegisTip"

    id          = Column(Integer,      primary_key=True, autoincrement=True)
    document_id = Column(Integer,      ForeignKey("AegisDocument.id"), nullable=False)
    position    = Column(SmallInteger, nullable=False)
    headline    = Column(Text,         nullable=False)
    body        = Column(Text,         nullable=False)
    links_json  = Column(JSONB,        nullable=True)

    document = relationship("AegisDocument", back_populates="tips")

    __table_args__ = (
        UniqueConstraint("document_id", "position", name="uq_tip_document_position"),
    )

    def to_dict(self) -> dict:
        """
        Serialize the tip for API responses.

        Returns:
            Dictionary with position, headline, body, and links.
        """
        return {
            "position": self.position,
            "headline": self.headline,
            "body":     self.body,
            "links":    self.links_json or [],
        }

    def __repr__(self) -> str:
        """
        Return a debug representation of the AegisTip instance.

        Returns:
            String with id, document_id, and position.
        """
        return f"<AegisTip(id={self.id}, doc={self.document_id}, pos={self.position})>"


class AegisDocumentAlert(Base):
    """
    Vulnerability alert associated with an AegisDocument.

    Comes from INCIBE or CIRCL/NVD. Each alert has an explicit position
    to preserve the order of appearance in the generated document.

    Attributes:
        id: Primary key, auto-incrementing integer.
        document_id: Foreign key to AegisDocument.id.
        position: Order of appearance (1-based).
        source: Alert source ('incibe' | 'circl').
        source_label: Human-readable source text ('INCIBE-CERT' | 'NVD/CVE').
        title: Alert title.
        published: Publication date.
        severity: Severity level ('crítica' | 'alta' | 'media' | 'baja' | NULL).
        affected_brands: Array of affected brands.
        description: Summary (≤ 500 chars).
        url: Link to original alert.

    Table Constraints:
        Unique constraint on (document_id, position) to prevent duplicates.
    """

    __tablename__ = "AegisDocumentAlert"

    id              = Column(Integer,       primary_key=True, autoincrement=True)
    document_id     = Column(Integer,       ForeignKey("AegisDocument.id"), nullable=False)
    position        = Column(SmallInteger,  nullable=False)
    source          = Column(String(16),    nullable=False)
    source_label    = Column(String(32),    nullable=False)
    title           = Column(String(256),   nullable=False)
    published       = Column(Date,          nullable=True)
    severity        = Column(String(16),    nullable=True)
    affected_brands = Column(ARRAY(String), nullable=True)
    description     = Column(Text,          nullable=True)
    url             = Column(String(512),   nullable=False)

    document = relationship("AegisDocument", back_populates="alerts")

    __table_args__ = (
        UniqueConstraint("document_id", "position", name="uq_alert_document_position"),
    )

    def to_dict(self) -> dict:
        """
        Serialize the alert for API responses.

        Returns:
            Dictionary with position, source, sourceLabel, title, published,
            severity, affectedBrands, description, and url.
        """
        return {
            "position":       self.position,
            "source":         self.source,
            "sourceLabel":    self.source_label,
            "title":          self.title,
            "published":      self.published.isoformat() if self.published else None,
            "severity":       self.severity,
            "affectedBrands": self.affected_brands or [],
            "description":    self.description,
            "url":            self.url,
        }

    def __repr__(self) -> str:
        """
        Return a debug representation of the AegisDocumentAlert instance.

        Returns:
            String with id, document_id, position, and source.
        """
        return (
            f"<AegisDocumentAlert(id={self.id}, "
            f"doc={self.document_id}, pos={self.position}, src='{self.source}')>"
        )