server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://seq:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /sentinel/ {
        proxy_pass http://seq:5000/sentinel/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /oauth/ {
        proxy_pass http://seq:5000/oauth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /aegis/ {
        proxy_pass http://seq:5000/aegis/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /users/ {
        proxy_pass http://seq:5000/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /acheron/ {
        proxy_pass http://seq:5000/acheron/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}